### ISSUE TITLE
Online Voting System

### ISSUE THREAD

**Issue by CodeWithCrescent** [crescent-php-pro/online-voting-system#1]
Welcome guys for any contribution to this project. It uses PHP and some js as backend and bootstrap 4 in front end.

**Comment by isaka-james** [comment]
Why you open the issue yourself :laughing: :laughing:

**Comment by CodeWithCrescent** [comment]
Hii ilikua kwaajiri ya kukusanya ideas kuhusu hii project, na kwa atakaye kua interested ili acomment hapa tucollaborate kuiimprove. That's all

**Comment by isaka-james** [comment]
Ndio muwe mnachat kwenye issues? 😂😂

**Comment by CodeWithCrescent** [comment]
Yah

**Comment by isaka-james** [comment]
It's better when you close the issue.

**Comment by CodeWithCrescent** [comment]
> It's better when you close the issue.

Ok
